site_name: The Algorithmic Mind
site_url: https://mydomain.org/mysite

plugins:
  - search
  - tags
  - blog


theme:
  name: material
  logo: home/images/neural.png
  favicon: home/images/neural.png
  palette:
    primary: purple
    scheme: slate
    accent: blue
  features:
    # - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.footer
extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

nav:
  - Home:  home/index.md
  - About Me:  home/about.md
  - Contact:  home/contact.md
  - Course:
    - course/index.md
    - course/lists/github.md
    - course/lists/python.md
    - course/lists/sql.md
    - course/lists/stat.md
    - course/lists/mlalgorithim.md
    - course/lists/deeplearning.md
  - Blog:
    - blog/index.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption