site_name: The Algorithmic Mind
site_url: https://mydomain.org/mysite

plugins:
  - search
  - tags
  - blog


theme:
  name: material
  logo: neural.png
  favicon: neural.png
  palette:
    primary: purple
    scheme: slate
    accent: blue
  features:
    # - toc.integrate
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - navigation.sections
    - navigation.prune
    - navigation.indexes

nav:
  - Home: index.md
  - About Me: about.md
  - Contact: contact.md
  - Blog:
    - blog/index.md
